### ISSUE TITLE
Report Bays mngt : display in wrong columns

### ISSUE THREAD

**Issue by blerohellec** [InfotelGLPI/racks#12]
versions 1.5.1 & 1.6.0
In the report 'Bays mngt', (rack's) place is displayed in column Position !
Position (of an item in rack) is displayed in column colonne U !
And (rack's) location is displayed in column Place !

**Comment by tsmr** [comment]
With last git version ?

**Comment by blerohellec** [comment]
yesterday version

**Comment by tsmr** [comment]
korial29 has corrected the report today. Can you check with his correction or add a screenshot to your issue please ?

**Comment by blerohellec** [comment]
Position and place were merely inverted in the report; it's now OK.

And I had a misunderstanding : in column Position, due to its name, I was expecting the position of an equipment in the rack; finally, it's the location of the rack. And in column U, I was expecting the nbr of Us occupied by the equipment; finally, it's the position of the equipment in the rack.

As a conclusion, the locale 'Position' is used to name 2 different things 
- the position of an equipment in a rack (tab front and rear)
- the column for location of a rack, in the report
  I consider that the 2nd one should be renamed to 'rack's location' for ex; An additional locale is necessary

**Comment by blerohellec** [comment]
Perfect
