### ISSUE TITLE
I could add an equipment although the position is occupied from the other side

### ISSUE THREAD

**Issue by blerohellec** [InfotelGLPI/racks#18]
v1.5 (0.85) & 1.6 (0.90)
i've got 2 equipment models, X occupies the full length of the rack (1 U), Y no (2 U).
in front panel, I add Y.
in rear panel, I could add X in the same position as Y ! Is it normal ?

I couldn't if both occupy the same nbre of U (let's say 1U & 1U)

**Comment by tsmr** [comment]
Plugin integrated into GLPI 9.3
I close
