### ISSUE TITLE
Manage racked blade servers in a blade frame (7U) itsef racked in a 42U rackable servers bay

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/racks#2]
Exemple concret :

Chassis lames = 7U pouvant contenir 10 lames (6U)

Ma baie 42U contient actuellement :
- espace libre
- serveur rackable
- serveur rackable
- serveur rackable
- mon chassis lame (7U) contenant lui-même : \* lame1 \* lame2 \* lame3 \* lame4 \* lame5 \* lame6 \* lame7 \* lame8 \* lame9 \* lame10

**Comment by plight** [comment]
This would be extremely helpful for dense datacenters.  Right now I get around it by making a rack with the specifications of the chassis (ie 10 u) and add the servers do it, then manually add a server and give it the model of the chassis, and assign that to a rack.

Its works, but is REALLY inefficient and kind of a mess when explaining to someone whats going on.
