### ISSUE TITLE
Install SQL errors

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/racks#21]
Install SQL errors

**Comment by drTr0jan** [comment]
The install doesn't work correctly.
There's an error during execution _empty-1.5.2.sql_:

> mysql> INSERT INTO `glpi_plugin_racks_configs` VALUES ('1', '1');
> ERROR 1136 (21S01): Column count doesn't match value count at row 1

You should use _INSERT INTO `glpi_plugin_racks_configs` VALUES (NULL,'1','1','1');_ instead.
