### ISSUE TITLE
Empty name and missing some buttons.

### ISSUE THREAD

**Issue by xxxadamtmg** [InfotelGLPI/racks#24]
I see only empty line on list when I try add object to rack, also missing  buttons from server side to add connection to rack (for temporary workaround I use search field on rack side).

GLPI 0.90 
Rack enclosures management  1.6.1
![rack](https://cloud.githubusercontent.com/assets/16130935/11555155/6ce87d18-999e-11e5-929d-43778e121ee8.gif)

**Comment by xxxadamtmg** [comment]
In meant time I upgraded GLPI to new version 0.90.1 and that file was changed so I probably can't try that fix.

**Comment by tsmr** [comment]
you can

**Comment by xxxadamtmg** [comment]
First I tried change file .../ajax/dropdownValue.php on test installation, that is why I mentioned about change GLPI version.  After some time I realized my mistake, and edited plugin dropdownValue.php file, now Rack Management display names correctly, thanx for fix.

**Comment by najib000** [comment]
Hi xxxadamtmg,

I have a question about your GLPI configuration.
I show that you manage your server assset on the below screenshot. Could you please tell me how can i do that ?

Many thanks
