### ISSUE TITLE
Problem Dropdown -> Places

### ISSUE THREAD

**Issue by cskarecki** [InfotelGLPI/racks#27]
Please can you fix problems with missing "Add" button on "Rack enclosures management" on Dropdowns Places, where is missing Add button.

**Comment by tsmr** [comment]
Can you add screenshot & give you glpi & plugins version please ?

**Comment by cskarecki** [comment]
Hi,

I add a picture, ver of GLPI is 0.90, and ver of plugin is "Rack enclosures management 1.6.1.".

Regards

Claudio

<img width="653" alt="glpi_places" src="https://cloud.githubusercontent.com/assets/17005970/12719341/bdcc504e-c8f4-11e5-8f1b-ecdfd210af58.PNG">

**Comment by tsmr** [comment]
Can you activate the debug mode for see if you have any errors ? & activate log into glpi for have logs into glpi/files/_log ?

**Comment by cskarecki** [comment]
This is production environment, can't do that right now.

**Comment by tsmr** [comment]
You can : debug mode is only for your glpi user (in preferences)

**Comment by cskarecki** [comment]
Hi here is from debug for dropdown racks:

1   SELECT `glpi_plugins`.\* 
FROM `glpi_plugins` 
WHERE `glpi_plugins`.`directory` = 'fusioninventory'    0.000  
2   SELECT `glpi_plugins`.\* 
FROM `glpi_plugins` 
WHERE `glpi_plugins`.`directory` = 'fusioninventory'    0.016  
3   SHOW TABLES LIKE '%glpi_plugin_fusioninventory_configs%'    0.000  
4   SELECT \* 
FROM `glpi_plugin_fusioninventory_configs`  0.000  
5   SELECT `glpi_plugins`.\* 
FROM `glpi_plugins` 
WHERE `glpi_plugins`.`directory` = 'racks'  0.000  
6   SELECT `glpi_plugins`.\* 
FROM `glpi_plugins` 
WHERE `glpi_plugins`.`directory` = 'racks'  0.000  
7   SHOW COLUMNS 
FROM `glpi_plugin_racks_roomlocations`  0.031   Table 'glpidb.glpi_plugin_racks_roomlocations' doesn't exist
8   SHOW COLUMNS 
FROM `glpi_plugin_racks_roomlocations`  0.000   Table 'glpidb.glpi_plugin_racks_roomlocations' doesn't exist
9   SHOW COLUMNS 
FROM `glpi_plugin_racks_roomlocations`  0.000   Table 'glpidb.glpi_plugin_racks_roomlocations' doesn't exist
10  SHOW COLUMNS 
FROM `glpi_plugin_racks_roomlocations`  0.016   Table 'glpidb.glpi_plugin_racks_roomlocations' doesn't exist
11  SHOW COLUMNS 
FROM `glpi_plugin_racks_roomlocations`  0.000   Table 'glpidb.glpi_plugin_racks_roomlocations' doesn't exist
12  SHOW COLUMNS 
FROM `glpi_plugin_racks_roomlocations`  0.016   Table 'glpidb.glpi_plugin_racks_roomlocations' doesn't exist

**Comment by cskarecki** [comment]
<img width="878" alt="glpi_debug" src="https://cloud.githubusercontent.com/assets/17005970/12742894/f1d55e54-c989-11e5-9e86-bec5efd9aa27.PNG">

**Comment by tsmr** [comment]
So you have a problem with your installation
you must create the table

```
CREATE TABLE IF NOT EXISTS `glpi_plugin_racks_roomlocations` (
   `id` int(11) NOT NULL auto_increment,
   `entities_id` int(11) NOT NULL default '0',
   `plugin_racks_roomlocations_id` int(11) NOT NULL default '0',
   `name` varchar(255) collate utf8_unicode_ci default NULL,
   `completename` text collate utf8_unicode_ci,
   `comment` text collate utf8_unicode_ci,
   `level` int(11) NOT NULL default '0',
   PRIMARY KEY  (`id`),
   UNIQUE KEY `unicity` (`entities_id`,`plugin_racks_roomlocations_id`,`name`),
   KEY `name` (`name`),
   KEY `plugin_racks_roomlocations_id` (`plugin_racks_roomlocations_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by cskarecki** [comment]
Thanks it works :+1:
