### ISSUE TITLE
GLPI 0.90.1 / Racks 1.6.1 Cannot create bay

### ISSUE THREAD

**Issue by magicbret** [InfotelGLPI/racks#28]
Hi,

I have several issues on my installation.
1. I cannot create location. The "Add" button is not displayed. 
2. I cannot configure the plugin. I've got the following error when i click on "Configuration"
The requested URL /glpi/plugins/racks/front/config.php was not found on this server.

Is there any issue with glpi 0.90.1 ?

Thanks

**Comment by magicbret** [comment]
Is there somebody to deal with the issues ?

**Comment by tdslot** [comment]
Yes, I have same problem. :( 

It is sad that author is not so responsive.

**Comment by tsmr** [comment]
try with 1.6.2

**Comment by magicbret** [comment]
Great ! Issue solved. Thanks
