### ISSUE TITLE
Adding devices in a rack : Dropdown list is strange

### ISSUE THREAD

**Issue by magicbret** [InfotelGLPI/racks#29]
Hi,

I have a strange behaviour when adding devices in a rack. Pictures is attached.

The model is well configured, but when i want to add a device, the list is blank but ican see all the lines. So it's difficult to choose a device.

Any help would be appreciated

Thanks
![sans titre](https://cloud.githubusercontent.com/assets/7100026/13074371/781b5732-d4a4-11e5-9eee-608570d6e524.png)

**Comment by tsmr** [comment]
see correction https://github.com/InfotelGLPI/racks/issues/22
