### ISSUE TITLE
Make dropdown Places translatable

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/racks#3]
Places is the only dropdown of the plugin which is not translatable

**Comment by tsmr** [comment]
To see too : 

From 0.85 on, Dropdowns are now translatable.
But available translations to current language of Models (computer, network, peripheral, other equipment) are not taken into account in 'Rack enclosure arrangement' (front/back).

Note it's correct in the report

**Comment by blerohellec** [comment]
OK for the models translations.
Places : in the report, take into account the translations (same for location, only in the report)

**Comment by blerohellec** [comment]
OK for places & locations translations in report.

One more thing I've just noticed : models translations are not used by the dropdown list proposed when I add an equipment.
Go to Front, choose Computer or Other equipment from the 1st list, then a 2nd list is proposed with the models of Computers or Other equipments. Here, translations are not used.
