### ISSUE TITLE
No Devices in drop list

### ISSUE THREAD

**Issue by tdslot** [InfotelGLPI/racks#30]
Hi,

I'm using GLPI 0.90.1 version with rack plugin 1.6.1. And want to add Device to rack, but it is no on list
![Rack list](https://ipfs.pics/ipfs/QmXc5UJu1691QkmqkPy9C3BsD1XFgvs8Ggw6mM4iYLsokZ)

Device is entered in inventory
![Device](https://ipfs.pics/ipfs/QmcgFKFFW5jRUjj4XkE93BZRXV34n9N4FZosURw1nhap3C)

My question is maybe is some required fields? Which should be filled or enough to fill device "Name" field to be listed in rack drop down list?

**Comment by tsmr** [comment]
see correction https://github.com/InfotelGLPI/racks/issues/22

**Comment by tdslot** [comment]
Hi,
Didn't help. Now and "Computers" drop down list is empty :( 
I chenged plugins/racks/ajax/dropdownValue.php lines 142-143

**Comment by tdslot** [comment]
Also on drop down list "Other equipments" display failed load. 

![Failed load](https://ipfs.pics/ipfs/QmQpToB8Wq9ienwSThCYTcSVnpuMcDjSSRm3Yo4uwSnQ9s)

This was before plugins/racks/ajax/dropdownValue.php file change.

**Comment by tdslot** [comment]
Hi @tsmr ,

Any suggestions?

**Comment by tdslot** [comment]
Maybe project is dead?

**Comment by tdslot** [comment]
Any progress...?

**Comment by tsmr** [comment]
If you have no items into drop down (without Loading failed error) you must add specifications for your computer model http://glpi/plugins/racks/front/itemspecification.php

Example : 
![image](https://cloud.githubusercontent.com/assets/13178158/13747314/f252b56e-e9f7-11e5-8071-b43ee477ae52.png)

**Comment by tdslot** [comment]
Hi,

When I try to add I can't add. There is no Save button as like in other places.
![No Save button](https://ipfs.pics/ipfs/QmWywqchu7sWpeaAQaEKDQPyXFkUSX2zvaeYnhDFcksCfu)

**Comment by tsmr** [comment]
No into computer models or networking models
![image](https://cloud.githubusercontent.com/assets/13178158/13747909/d0380c88-e9fa-11e5-92d6-bb5b3e938539.png)

**Comment by tsmr** [comment]
For other equipements verify if the table exists : glpi_plugin_racks_others please

**Comment by tdslot** [comment]
Thank you @tsmr probably is my problem that I didn't know how to use properly your plugin :)
Now I got something in dropdown list :)

**Comment by tsmr** [comment]
;)

**Comment by tdslot** [comment]
Hi,

After upgrade GLPI to 90.4 this issue appears again.

I have model specification
![GLPI models](https://ipfs.pics/ipfs/Qmbj8eGKjcHyXDFHMEE7CKaDAHUSnQypt1aWbpG7Ysfm8V)

, I can't see in drop down list.
![GLPI Rack](https://ipfs.pics/ipfs/QmbW73QYeSv3LppUCxrd2mn6JhT6FzNSnR6ShRHViF5E7x)

What and where I can check and fix?

Tadas
