### ISSUE TITLE
In "Power supply connection" not possible add item

### ISSUE THREAD

**Issue by tdslot** [InfotelGLPI/racks#31]
Hi,

I just want to add in "Power supply connection" record, but it not possible add
![No Save button](https://ipfs.pics/ipfs/QmRWnE8nhjZwZaoMhpvUb6TxCwVHuYjDbnx6MjJ78g7XKB)

And when in input field "Name" I press enter I get this error
![No Permission](https://ipfs.pics/ipfs/QmPjZjLcaeWcrLprSFnCZtxFDkbfUSFFSrC4kECFuLDiSi)

Where I should look for permission? I checked couple times couldn't find.

**Comment by tsmr** [comment]
In Debug mode ? any errors on form ?

**Comment by tdslot** [comment]
How Can I tun on Debug mode?

**Comment by tsmr** [comment]
Into your preferences

**Comment by tdslot** [comment]
Table 'itsm.glpi_plugin_racks_connections' doesn't exist

**Comment by tdslot** [comment]
where I can find table creation SQL ?

**Comment by tsmr** [comment]
```
CREATE TABLE IF NOT EXISTS `glpi_plugin_racks_connections` (
   `id` int(11) NOT NULL auto_increment,
   `name` varchar(255) collate utf8_unicode_ci default NULL,
   `comment` text collate utf8_unicode_ci,
   PRIMARY KEY  (`id`),
   KEY `name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by tdslot** [comment]
Now works after creating

Same problem is with:
Table 'its.glpi_plugin_racks_roomlocations' doesn't exist
Table 'its.glpi_plugin_racks_othermodels' doesn't exist
Table 'its.glpi_plugin_racks_racktypes' doesn't exist
Table 'its.glpi_plugin_racks_rackstates' doesn't exist

**Comment by tsmr** [comment]
Sure, you probably have a problem of install the plugin (perhaps with mysql strict mode)
