### ISSUE TITLE
Missing units ()

### ISSUE THREAD

**Issue by Megachip** [InfotelGLPI/racks#34]
In version 1.6.2 missing unites for Calorific waste, Flow Rate and Weight in brackets.
Seems fine in 1.5.0

`*** PHP Notice(8): Undefined index: N/A
  Backtrace :
  plugins/racks/inc/config.class.php:124             
  plugins/racks/inc/itemspecification.class.php:292  PluginRacksConfig->getUnit()
  plugins/racks/inc/itemspecification.class.php:63   PluginRacksItemSpecification->showForm()
  inc/commonglpi.class.php:469                       PluginRacksItemSpecification::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
`

**Comment by amma35** [comment]
Did you have any errors during the upgrade?

**Comment by tsmr** [comment]
Plugin integrated into GLPI 9.3
I close
