### ISSUE TITLE
Short 'name' filed in a rack front/back enclosure arrangement

### ISSUE THREAD

**Issue by drTr0jan** [InfotelGLPI/racks#36]
The 'name' field length is short (10 symbols). It is very unuseable.
I suggest expand the filed length. Ex, upper to 20 symbols.

It's need replace _778:inc/rack_item.class.php_:
`echo "<td class='center'><input type='text' name='name".$data["id"]."' value='".$PluginRacksOther->fields["name"]."' size='20'></td>";`

**Comment by amma35** [comment]
Done in commit e4510603df4697a379374d1b631e5a60cb8afa4b
