### ISSUE TITLE
No Dropdown list

### ISSUE THREAD

**Issue by tdslot** [InfotelGLPI/racks#37]
Hi,

After upgrade GLPI to 90.4 this issue appears again.

I have model specification
![GLPI models](https://ipfs.pics/ipfs/Qmbj8eGKjcHyXDFHMEE7CKaDAHUSnQypt1aWbpG7Ysfm8V)

, I can't see in drop down list.
![GLPI Rack](https://ipfs.pics/ipfs/QmbW73QYeSv3LppUCxrd2mn6JhT6FzNSnR6ShRHViF5E7x)

What and where I can check and fix?

Tadas

**Comment by ashmonger** [comment]
Same here. GLPI 0.90.4 and Racks 1.6.2.

**Comment by tsmr** [comment]
Errors into glpi/files/_log ?

**Comment by tdslot** [comment]
If it will be helpful here is log:

```
2016-07-25 20:20:43 [6@www]
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  plugins/racks/front/rack.form.php:82
2016-07-25 20:20:43 [6@www]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/racks/front/rack.form.php:85
2016-07-25 20:20:43 [6@www]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/racks/front/rack.form.php:86
2016-07-25 20:20:45 [6@www]
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  plugins/racks/front/rack.form.php:82
2016-07-25 20:20:45 [6@www]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/racks/front/rack.form.php:85
2016-07-25 20:20:45 [6@www]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/racks/front/rack.form.php:86
2016-07-25 22:52:43 [8@www]
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  inc/dbmysql.class.php:240
  plugins/fusioninventory/inc/menu.class.php:875     DBmysql->numrows()
  plugins/fusioninventory/front/menu.php:50          PluginFusioninventoryMenu::board()
2016-07-25 22:53:26 [8@www]
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  inc/dbmysql.class.php:240
  plugins/fusioninventory/inc/menu.class.php:875     DBmysql->numrows()
  plugins/fusioninventory/front/menu.php:50          PluginFusioninventoryMenu::board()
2016-07-25 22:56:46 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:17 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:17 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:45 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:45 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:45 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:52 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
2016-07-25 22:57:52 [8@www]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  plugins/archires/inc/imageitem.class.php:164
  plugins/archires/front/config.form.php:120         PluginArchiresImageItem->showConfigForm()
```

**Comment by tsmr** [comment]
No sql-errors ?

**Comment by tdslot** [comment]
Related with yesterday my changes only couple sql errors but probably is not related with racks.

```
2016-07-25 22:52:43 [8@www]
  *** MySQL query error:
  SQL: SELECT `glpi_networkports`.`id` FROM `glpi_networkports`
              LEFT JOIN `glpi_plugin_fusioninventory_networkports`
                 ON `glpi_plugin_fusioninventory_networkports`.`networkports_id` = `glpi_networkports`.`id`
              LEFT JOIN glpi_networkports_networkports
                  ON (`networkports_id_1`=`glpi_networkports`.`id`
                     OR `networkports_id_2`=`glpi_networkports`.`id`)
              WHERE `glpi_plugin_fusioninventory_networkports`.`id` IS NOT NULL
                  AND `glpi_networkports_networkports`.`id` IS NOT NULL
                   AND ( `networkports`.`entities_id` IN (\'0\')  )
  Error: Unknown column 'networkports.entities_id' in 'where clause'
  Backtrace :
  plugins/fusioninventory/inc/menu.class.php:874
  plugins/fusioninventory/front/menu.php:50          PluginFusioninventoryMenu::board()
2016-07-25 22:53:26 [8@www]
  *** MySQL query error:
  SQL: SELECT `glpi_networkports`.`id` FROM `glpi_networkports`
              LEFT JOIN `glpi_plugin_fusioninventory_networkports`
                 ON `glpi_plugin_fusioninventory_networkports`.`networkports_id` = `glpi_networkports`.`id`
              LEFT JOIN glpi_networkports_networkports
                  ON (`networkports_id_1`=`glpi_networkports`.`id`
                     OR `networkports_id_2`=`glpi_networkports`.`id`)
              WHERE `glpi_plugin_fusioninventory_networkports`.`id` IS NOT NULL
                  AND `glpi_networkports_networkports`.`id` IS NOT NULL
                   AND ( `networkports`.`entities_id` IN (\'0\')  )
  Error: Unknown column 'networkports.entities_id' in 'where clause'
  Backtrace :
  plugins/fusioninventory/inc/menu.class.php:874
  plugins/fusioninventory/front/menu.php:50          PluginFusioninventoryMenu::board()
```

**Comment by tsmr** [comment]
Nothing related to plugin racks. Have you some networking elements which have 3500ul-48G model assigned ?

**Comment by ashmonger** [comment]
The same thing happen for me, for networking elements AND computers.
The installation is pretty new and there is not a lot of stuff inside.

php-errors.log

2016-07-26 03:47:11 [6@glpi]
  **\* PHP Notice(8): Undefined variable: nb
  Backtrace :
  inc/infocom.class.php:150
  inc/commonglpi.class.php:208                       Infocom->getTabNameForItem()
  plugins/racks/inc/rack.class.php:187               CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:158                       PluginRacksRack->defineTabs()
  inc/commonglpi.class.php:689                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1132                      CommonGLPI->showTabsContent()
  plugins/racks/front/rack.form.php:165              CommonGLPI->display()
2016-07-26 03:47:15 [6@glpi]
  **\* PHP Notice(8): Undefined variable: nb
  Backtrace :
  inc/infocom.class.php:150
  inc/commonglpi.class.php:208                       Infocom->getTabNameForItem()
  plugins/racks/inc/rack.class.php:187               CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:158                       PluginRacksRack->defineTabs()
  ajax/updatecurrenttab.php:51                       CommonGLPI->defineAllTabs()
2016-07-26 03:47:28 [6@glpi]
  **\* PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/racks/front/rack.form.php:85
2016-07-26 03:47:28 [6@glpi]
  **\* PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/racks/front/rack.form.php:86
2016-07-26 03:47:28 [6@glpi]
  **\* PHP Notice(8): Undefined variable: nb
  Backtrace :
  inc/infocom.class.php:150
  inc/commonglpi.class.php:208                       Infocom->getTabNameForItem()
  plugins/racks/inc/rack.class.php:187               CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:158                       PluginRacksRack->defineTabs()
  inc/commonglpi.class.php:689                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1132                      CommonGLPI->showTabsContent()
  plugins/racks/front/rack.form.php:165              CommonGLPI->display()

**Comment by tdslot** [comment]
No. Just simply this network device and Specification data as show in screenshots before.

I having this error but probably is not related also with Racks plugin
![Network - Documents](https://ipfs.pics/ipfs/QmQneikmLcM8N969bDHxJKSvwhKA6DUtaEzVmwruJdYMeJ)

This error on all network devices.

**Comment by tsmr** [comment]
Yes but for display network devices into dropdown, you must have network devices which have model associated

**Comment by tdslot** [comment]
Yes as you explained.
1. Network device have entry in networks device;
2. Have model:
   ![Network device model](https://ipfs.pics/ipfs/QmSt7nmEph4J4YaAb32QdQLsiKSgujfcPcdsybmoQaJMGb)
3. Have specification:
   ![GLPI models](https://ipfs.pics/ipfs/Qmbj8eGKjcHyXDFHMEE7CKaDAHUSnQypt1aWbpG7Ysfm8V)

And no in racks drop list.
![GLPI Rack](https://ipfs.pics/ipfs/QmbW73QYeSv3LppUCxrd2mn6JhT6FzNSnR6ShRHViF5E7x)

**Comment by ashmonger** [comment]
OK, I understand how it works.
You should have something like a tutorial to explain it.

And now it works.

**Comment by tdslot** [comment]
I just reinstalled Racks plugin and enter data again. And I getting same result  :flushed:

**Comment by tdslot** [comment]
What requirement should be met to find devices in this list?

**Comment by tdslot** [comment]
Other thing,

When I want delete specification data it does not delete.
![Datele Spec](https://ipfs.pics/ipfs/QmYr68Dd55syG1eJsYJqrEmrGsb5DVR8L4ASW5GwPypTWH)

**Comment by tdslot** [comment]
Hi,

Finally found root of the problem.  Those switches was on different "Entity" not in Root Entity.

I think need some documentation or some warning in Rack plugin or some visual identification. Because almost not clear how to do or use.
