### ISSUE TITLE
3 problèmes pour Racks 1.7.0 dans GLPI 9.1

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/racks#39]
bonjour

Le premier problème quand je vais dans Baie -> Configuration. 
Si je modifie n'importe quel champ. Exemple : Configuration des unités. Je choisis Français j'enregistre. Cela revient automatiquement à Anglaise

2e problème :  
Dans Baie -> Spécifications de modèles -> Ajouter de nouveaux modèles. Il me renvoie sur une liste vide alors que j'en ai déjà créé.

3e problème : 
Pour un modèle d'ordinateur que j'ai déjà renseigné. Impossible d'avoir le serveur portant ce numéro de modèle lorsque je suis dans la Baie et que je fais Ordinateurs puis qu'il me donne la liste des différents serveurs à disposition.

Sinon ce plugin est superbe et bien pratique. L'ajout dans les baies pour les modèles qui sont référencés se fait sans problème.

**Comment by tsmr** [comment]
Merci d'activer le mode debug - a mon avis c'est des erreurs sur des tables Myql

**Comment by sebfun** [comment]
alors j'ai activé le mode debug.
Sur la page de configuration : 
Configuration
Configuration des unités  
Copier le lieu de la baie à l'ajout d'un objet dans la baie  
PHP Notice: Undefined index: add_location_on_new_item in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 75
Mettre à jour le lieu des éléments lors de la modification du lieu de la baie  
PHP Notice: Undefined index: forward_location_on_change in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 84

Sur la ligne où l'on choisi Métrique ou Anglaise, il y a aussi la même erreur dans le même fichier mais à la ligne 107.

Dans l'affichage d'une baie, j'ai ceci : 
    Largeur 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
Numéro de série       Hauteur 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
Numéro d'inventaire        Poids  
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
Modèle 
    Profondeur  
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124

Nombre d'alimentations  Courant consommé   Dissipation calorifique Débit d'air frais  Poids
0   0.00 amps   0.00 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
    0.00 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
    0.00 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124

```
Largeur 
```

PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
Numéro de série       Hauteur 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
Numéro d'inventaire        Poids  
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
Modèle 
    Profondeur  
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124

Nombre d'alimentations  Courant consommé   Dissipation calorifique Débit d'air frais  Poids
0   0.00 amps   0.00 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
    0.00 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
    0.00 
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124

Dans l'onglet "Avant" : 
Disposition de la baie:
    Position    Nom Type    Modèle Connexion alimentation 1    Connexion alimentation 2    Cordons
nécessaires    Courant consommé
(amps)  Dissipation calorifique
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Débit d'air frais
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Poids
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)

Dans l'onglet "Arrière" : 
Disposition de la baie:
    Position    Nom Type    Modèle Connexion alimentation 1    Connexion alimentation 2    Cordons
nécessaires    Courant consommé
(amps)  Dissipation calorifique
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Débit d'air frais
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Poids
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)

Dans Spécifications :
    Equipement  Courant consommé
(amps)  Nombre d'alimentations  Dissipation calorifique
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Débit d'air frais
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Taille (U)  Poids
(
PHP Notice: Undefined index: N/A in D:\xampp\htdocs\glpi\plugins\racks\inc\config.class.php at line 124
)   Prend toute la longueur de la baie

Dans Modèles d'ordinateurs pas d'erreur PHP ni SQL mais aucune donnée affichée

Merci d'avance pour votre aide.

**Comment by tsmr** [comment]
C’était un update ? ou une nouvelle installation ?

**Comment by sebfun** [comment]
désolé pour la réponse tardive. C'était un update.

**Comment by tsmr** [comment]
A partir de quelle version ?

**Comment by sebfun** [comment]
j'ai fait un update depuis GLPI 0.90 avec le plugin qui était en 1.6.1

**Comment by amma35** [comment]
Une modification est a faire dans le fichier glpi/plugins/racks/hook.php 
Voir le commit joint

**Comment by sebfun** [comment]
Modification effectuée mais ne fonctionne pas pour le problème numéro 1

**Comment by amma35** [comment]
Pouvez-vous me fournir les fichiers de logs files/php-errors.log et sql-errors.log mais sans les logs avant la modification.

**Comment by sebfun** [comment]
php-log : 
```
2017-10-12 15:23:40 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: unit
  Backtrace :
  plugins\racks\inc\config.class.php:107             
  plugins\racks\inc\config.class.php:57              PluginRacksConfig->isMetricUnit()
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:40 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: unit
  Backtrace :
  plugins\racks\inc\config.class.php:107             
  plugins\racks\inc\config.class.php:62              PluginRacksConfig->isMetricUnit()
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:40 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: add_location_on_new_item
  Backtrace :
  plugins\racks\inc\config.class.php:75              
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:40 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: forward_location_on_change
  Backtrace :
  plugins\racks\inc\config.class.php:84              
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:57 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: unit
  Backtrace :
  plugins\racks\inc\config.class.php:107             
  plugins\racks\inc\config.class.php:57              PluginRacksConfig->isMetricUnit()
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:57 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: unit
  Backtrace :
  plugins\racks\inc\config.class.php:107             
  plugins\racks\inc\config.class.php:62              PluginRacksConfig->isMetricUnit()
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:57 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: add_location_on_new_item
  Backtrace :
  plugins\racks\inc\config.class.php:75              
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
2017-10-12 15:23:57 [6@Firefox_52]
  *** PHP Notice(8): Undefined index: forward_location_on_change
  Backtrace :
  plugins\racks\inc\config.class.php:84              
  plugins\racks\front\config.form.php:42             PluginRacksConfig->showForm()
```

pas de fichier sql-errors dans le répertoire log

**Comment by amma35** [comment]
Avec la correction vous êtes repartis sur une ancienne version de la base de données ou vous avez juste apporter la correction sans effectuer de mise à jour du plugin ?

**Comment by sebfun** [comment]
j'ai juste apporté la modification sans maj du plugin

**Comment by amma35** [comment]
C'est normalement que vous ayez les mêmes erreurs, la modification n'a rien changé en base de données.

Soit vous repartez d'une ancienne version de la base de données.
Ou vous changez le numéro de version du plugin pour effectuer la mise à jour et il faut bien remettre la version qui était présente avant la modification.
Pour cela il faut changer dans le fichier setup.php ligne 100 : 
`'version'        => '1.7.0',` en modifiant le numéro de version

**Comment by sebfun** [comment]
Bonjour
Je pense que je n'ai pas bien compris car dans le fichier l'information se trouve à la ligne 101 et est déjà renseignée comme vous indiquez 

> function plugin_version_racks() {
   return array ('name'           => _n('Rack enclosure management',
                                        'Rack enclosures management',
                                        2, 'racks'),
                  'version'        => '1.7.0',

**Comment by amma35** [comment]
Oui il faut que vous changiez ce numéro de version en 1.7.1 par exemple.

**Comment by sebfun** [comment]
si je mets 1.7.1. il me dit ensuite "Merci d'activer le plugin"
Quand je vais dans Plugins il me dit "Mettre à jour".
Ce que j'ai fait et ensuite il dit "Traitement en cours" puis rien ne se passe. La page ne se recharge pas.

**Comment by sebfun** [comment]
J'ai ensuite remis la bonne version puis de nouveau Mise à jour et rien ne se passe...

**Comment by amma35** [comment]
En faisant ces manipulations avez-vous des erreurs dans les fichiers de log ? 

Sinon mettez-vous en mode debug => préférences utilisateurs => mode = debug. 
Cela vous permettras de voir les erreurs.

**Comment by sebfun** [comment]
Je n'ai pas regardé car j'ai dû faire désinstaller puis réinstaller et activer. J'ai perdu toute la configuration
