### ISSUE TITLE
Migration from v1.4.1 to v1.7.0 (SQL Errors)

### ISSUE THREAD

**Issue by tabad** [InfotelGLPI/racks#40]
# The environment

  * Source
    * Red Hat Enterprise Linux Server release 6.3 (Santiago)
        * GLPI v0.84.8
            * Rack Enclosures Management v1.4.1
  * Target
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
            * Rack Enclosures Management v1.7.0

Notes

  1. The GLPI core tables (`^glpi_(?!plugin_).*$` tables) were migrated from GLPI v0.84.8 to GLPI v9.1.2 without any problem; files `php-errors.log`and `sql-errors.log` where empty after migration process.
  
# The issue

The migration process from *Rack Enclosures Management* v1.4.1 to  v1.7.0 creates a lot of entries into `sql-errors.log` file.

I'm including [racks-1.4.1-to-1.7.0.zip](https://github.com/InfotelGLPI/racks/files/729867/racks-1.4.1-to-1.7.0.zip) with all the information.

**Comment by amma35** [comment]
Une modification est a faire dans le fichier glpi/plugins/racks/hook.php
Voir le commit joint
