### ISSUE TITLE
Add new device

### ISSUE THREAD

**Issue by HairullinRR** [InfotelGLPI/racks#41]
GLPI 9.1.2
plugin ver. 1.7.0
Can not add a device!
![rack](https://cloud.githubusercontent.com/assets/25144072/23116718/e7bc117a-f76d-11e6-887c-e371609391a9.PNG)

**Comment by Bullot78** [comment]
Hi,
did you follow the manual?
Creating a computer template, link it to a computer?
Also be sure that your rack and your server are in the same entity and at same location.

Regards

**Comment by pepinov** [comment]
Hello, 
I've the same problem. Network device and rack is at the same location, but don't know what do you mean the same entity?
Regards
Josef

**Comment by fpusersuggest** [comment]
# Where is the manual ?

**Comment by amma35** [comment]
There is no manual.
An explanation of this issue: https://github.com/InfotelGLPI/racks/issues/48

**Comment by amma35** [comment]
Is it good for use?
