### ISSUE TITLE
One slot as disappeared from my 42U rack

### ISSUE THREAD

**Issue by Bullot78** [InfotelGLPI/racks#42]
Hello,

i'm using glpi 0.9.1.2 with racks 1.7.0.

I have created a rack with 42U.
I have added a network device on slot 41 on rear view.
I have moved the device and the rack through entities and locations.
Now slot 41 is no more visible.
I have tried to remove the device from network equipment\baie tab but even i can't see anymore the rack at equipment level, the slot is still no visible and i'm not able to add the equipment again.

![image](https://cloud.githubusercontent.com/assets/22710368/23226984/d37f63c6-f937-11e6-9be4-92e88f4ba754.png)

 I have tried to have a look at the database tables but was unable to find in which is stored the information regarding slot position.

Any help would be greatly appreciated.

Many thanks.

**Comment by Bullot78** [comment]
J'ai  trouvé d'où vient le bug.
Le plugin ne voit que les modèles qui ont des paramètres dans l'onglet spécifications mais pas les modèles déjà présents dans GLPI.
J'avais donc créé un doublon du modèle d'équipement sans le savoir.
J'ai renommé le modèle et visiblement cela n'a pas suivi, dans la fiche de l'équipement c'est l'ancien nom qui apparaissait toujours.
En mettant à jour le modèle au niveau de l'équipement je vois le slot de nouveau et j'ai pu ajouter de nouveau l'équipement.

Pourrais-je savoir dans quelle table est stockée l'information sur l'emplacement de l'équipement dans la baie ?

Merci

**Comment by bruce79** [comment]
Hi,

I'm having the same problem (I created a switch as test, and placed it in the rack), afterwards I deleted te switch.  And it dissapears from the webpage (but not in the tables)

First I'm not a developer, just a user from glpi, but this is how I solved it:

![image](https://user-images.githubusercontent.com/24406522/26969139-fadfe082-4d04-11e7-96dc-e72b6f7d7814.png)

As you can see the OU 42 is unavailable (my rack is called 'S1-RACK-3')

SELECT id FROM glpi.glpi_plugin_racks_racks where name='S1-RACK-3';
this gives me id 5

SELECT * FROM glpi.glpi_plugin_racks_racks_items where plugin_Racks_racks_id=5;
show me that there is a device (with id 89 in position  42)
![image](https://user-images.githubusercontent.com/24406522/26969771-3258b6c2-4d07-11e7-812f-315c71a5703a.png)

I check if the device still exists (type is NetworkEquipmentModel so i look in the table glpi_networkequipments)

SELECT * FROM glpi.glpi_networkequipments where id = 89 or id = 91;

as you can see the id 89 doesn't exist anymore and id 91 does exist (look in the screenshot above equipment with id 91 is in slot 43)

I delete the record:
delete from glpi.glpi_plugin_racks_racks_items  where id = 24;

(I refresh my browser)

And u42 is back.
![image](https://user-images.githubusercontent.com/24406522/26970090-5571c864-4d08-11e7-8f32-7f506a34aefe.png)

**Comment by amma35** [comment]
La table ou est stocké l'équipement est la table glpi_plugin_racks_racks_items.
@Bullot78 Le problème est-il résolu ?
