### ISSUE TITLE
Comment lier une baie à des équipements ?

### ISSUE THREAD

**Issue by csteph85** [InfotelGLPI/racks#48]
@amma35 Désolé, ce n'est pas vraiment une issue, mais je ne comprends pas comment lier une baie à du matériel ou inversement.

J'ai du matériel réseau, une baie, le tout dans le même lieu au sens de GLPI et je ne vois pas comment indiquer que tel matériel est dans la baie. Je vois simplement un "Merci de configurer les spécifications des modèles de matériel avant de les associer" mais je ne vois pas comment faire.

J'utilise la dernière version du module avec GLPI 9.1.4.

Merci d'avance

![prtscr capture](https://user-images.githubusercontent.com/5772395/27739909-798efe66-5db0-11e7-9165-4c3e1b1cfa40.jpg)

**Comment by amma35** [comment]
Bonjour,

Il faut dans un premier temps ajouter les spécifications des modèles pour cela aller dans Parc > Baies > Spécification de modèles d'équipement.

![2017-08-03 09_27_47-glpi - baies](https://user-images.githubusercontent.com/15138371/28910709-412c388e-782e-11e7-8e7c-e42fc703e9f3.png)

Il faut ensuite Ajouter des nouveaux modèles dans chaque type. 

Dans chaque modèle, il faut préciser les spécifications pour chaque modèle : 
![2017-08-03 09_31_01-glpi - modeles de materiels reseau - 15](https://user-images.githubusercontent.com/15138371/28910787-8878da9e-782e-11e7-9b56-d4bebccdbbf8.png)

**Comment by amma35** [comment]
Est-ce que c'est bon ? 
Je cloture l'issue.

**Comment by ekip-94** [comment]
Quelqu'un peut me dire ce qu'il faut que je fasse une fois que j'ai ajouter une baie svp ???

**Comment by amma35** [comment]
Il faut ouvrir une nouvelle issue et developper d'avantage votre problématique
