### ISSUE TITLE
Fatal sql errors when export report in pdf

### ISSUE THREAD

**Issue by tsmr** [InfotelGLPI/racks#5]
I'm running version 1.5.0 of the plugin

Report - Bays mngt
export to PDF (portrait or landscape)
Sql errors beginning with

PHP Warning(2): include(/var/www/glpi085/lib/ezpdf/class.ezpdf.php): failed to open stream: No such file or directory

See screenshot attached
No Pdf is generated.

Indeed, I could not find class.ezpdf.php !
Is something missing ?

**Comment by tsmr** [comment]
Sql errors in report - Bays mngt (export in csv)

I'm running version 1.5.0 of the plugin.

Report - Bays mngt
Export in Csv
3 parameters are requested : encoding, quotes, end of line
Click green button 'Export' -> 2 sql errors (extract hereafter)

It seems that in /inc/report.class.php, line 331, a parameter (the 4th) is missing in call to function ShowTitle, for group.

PHP Notice(8): Undefined index: quotes 
Backtrace : 
plugins/racks/inc/report.class.php:701 
plugins/racks/inc/report.class.php:639 PluginRacksReport::showHeaderItem() 
plugins/racks/inc/report.class.php:331 PluginRacksReport->showTitle() 
plugins/racks/front/report.php:68 PluginRacksReport->showResult()
PHP Notice(8): Undefined index: encoding 
Backtrace : 
plugins/racks/inc/report.class.php:705 
plugins/racks/inc/report.class.php:639 PluginRacksReport::showHeaderItem() 
plugins/racks/inc/report.class.php:331 PluginRacksReport->showTitle() 
plugins/racks/front/report.php:68 PluginRacksReport->showResult()

**Comment by tsmr** [comment]
already corrected

**Comment by blerohellec** [comment]
Both corrected
