### ISSUE TITLE
Bug sur position des éléments après remplacement - GLPI 9.1.2 / Rack 1.7.0

### ISSUE THREAD

**Issue by PierreTeclib** [InfotelGLPI/racks#50]
Bonjour,

Nous avons constaté un bug dans le plugin Rack / Baie Management. 
En effet, lorsque nous supprimons un équipement dans la baie et que nous souhaitons en placer un autre à sa place, sa position disparaît. Par exemple, dans les screenshots ci-joint on voit qu'il y avait un firewall en position 4U et qu’après l'avoir supprimé, la position ne revient pas et ne s'affiche pas dans la liste déroulante.

![baie](https://user-images.githubusercontent.com/6872020/30329493-b2a9e7c2-97d2-11e7-907a-a5668e42c3ef.png)
![baie2](https://user-images.githubusercontent.com/6872020/30329491-b299cdd8-97d2-11e7-9828-4b4d7cf7d89b.png)
![baie3](https://user-images.githubusercontent.com/6872020/30329492-b29af21c-97d2-11e7-8dd2-6c1f496f185a.png)

**Comment by amma35** [comment]
Bonjour,

Avez-vous des erreurs dans les fichiers files/_log/php-errors.log et sql-errors.log ?

**Comment by amma35** [comment]
Je ferme pour l'instant sans réponse, n'hésitez pas à rouvrir si le problème persiste.
