### ISSUE TITLE
Multiple devices on the same level

### ISSUE THREAD

**Issue by novalenik** [InfotelGLPI/racks#52]
Hello.
Can I make multiple devices appear on the same level? For the case when they stand on the shelf.

Modem Switch Mediaconverter       } 1U
=====================    <-- rack

Google Translate rulezzz!!!

**Comment by amma35** [comment]
No you can not add more equipment to the same position.

**Comment by C-Duv** [comment]
@novalenik, see [_GLPI Datacenters management_](https://github.com/glpi-project/spec/wiki/GLPI-Datacenters-management/) specifications proposal for enhancement on this part.
