### ISSUE TITLE
Linked port assignments

### ISSUE THREAD

**Issue by sweber64** [InfotelGLPI/racks#53]
This is a fantastic plugin, but there is one feature that it is missing to make it truly great, and that is to be able to have port assignments linked across devices, such as from switch to server or storage appliance.  I notice a lot of other rack management software has this feature, will this ever be added to this plugin?  And is there an estimated ETA for the release of this plugin for GLPI version 9.2?

**Comment by amma35** [comment]
(not the plugin) But already with GLPI you can connect objects with their networpport.
