### ISSUE TITLE
Dropdown lists not working

### ISSUE THREAD

**Issue by grego1981** [InfotelGLPI/racks#54]
Hello, I cannot add anything in the dropdowns of the module because no add bautton appears. How to fix it? Tried via quick add, from the dropdowns manu and from the i button with the same results no add button.

- The version of the plugin. 1.8.0
- The version of your GLPI. 9.2

![capture](https://user-images.githubusercontent.com/9021998/32551037-dfae5b62-c497-11e7-82b0-495f7b060c5e.PNG)

Thank you and BR 
Gregory

**Comment by amma35** [comment]
Have you errors in apache or glpi logs ?

**Comment by grego1981** [comment]
Goodmorning and sorry for the delay.

The message in php-errors.log when trying to access the status is:

2017-11-09 08:26:22 [7@itsrv-05]
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  inc/commondbtm.class.php:2356
  inc/commondropdown.class.php:239                   CommonDBTM->showFormHeader()
  front/dropdown.common.form.php:124                 CommonDropdown->showForm()
  plugins/racks/front/racktype.form.php:33           include()
2017-11-09 08:26:22 [7@itsrv-05]
  *** PHP User Warning(512): Table glpi_plugin_racks_racktypes does not exists
  Backtrace :
  :
  inc/dbmysql.class.php:756                          trigger_error()
  inc/commondropdown.class.php:144                   DBmysql->fieldExists()
  inc/commondropdown.class.php:241                   CommonDropdown->getAdditionalFields()
  front/dropdown.common.form.php:124                 CommonDropdown->showForm()
  plugins/racks/front/racktype.form.php:33           include()
2017-11-09 08:26:22 [7@itsrv-05]
  *** PHP Notice(8): Undefined index: comment
  Backtrace :
  inc/commondropdown.class.php:256
  front/dropdown.common.form.php:124                 CommonDropdown->showForm()
  plugins/racks/front/racktype.form.php:33           include()

It seems like some tables are missing, the problem is that no error was shown when installing or updating the plugin.

**Comment by grego1981** [comment]
Just unistalled completetly and reinstalled the plugin and it seems to have created correctly all the needed tables. The previous installation was an upgrade from previous release version.

**Comment by amma35** [comment]
did you upgrade from version 1.7.0 to 1.8.0?

**Comment by grego1981** [comment]
Yes.

**Comment by tsmr** [comment]
Plugin integrated into GLPI 9.3
I close
