### ISSUE TITLE
Menu déroulant materiel 

### ISSUE THREAD

**Issue by Lunaty** [InfotelGLPI/racks#55]
Bonjour , 

Je viens vous reporter une erreur que je rencontre . 

- Plugin Version 1.8
- GLPI 9.2.1

Lorsque je veux ajouter un matériel a une baie je clic sur le menu dans ajout d'équipements . Je sélectionne une catégorie (Qui n'est pas vide) et je n'ai pas le menu déroulant qui s'affiche . 

![bug1](https://user-images.githubusercontent.com/36630765/36380487-c9591550-1582-11e8-849d-325aeedc033a.png)

Après une actualisation avec la même manipulation il s'affiche vide .

![bug2](https://user-images.githubusercontent.com/36630765/36380625-45972350-1583-11e8-9316-9d105403abcf.PNG)

Voici les log apache .

[Mon Feb 19 10:09:17.224054 2018] [:error] [pid 4188] [client 10.201.10.22:59076] PHP Warning:  error_log(/var/www/glpi/files/_log/php-errors.log): failed to open stream: Permission denied in /var/www/glpi/inc/toolbox.class.php on line 500, referer: http://glpi.XXX/plugins/racks/front/rack.form.php?id=1

Il y a une erreur de droit mais je ne sais pas à quelle niveau .

Merci par avance .

Cordialement .

**Comment by amma35** [comment]
Bonjour,

GLPI n'a pas le droit d'écrire dans le fichier de logs pour connaitre l'erreur PHP du plugin, il faut d'abord que GLPI puisse écrire dans les fichiers de logs.

**Comment by Lunaty** [comment]
Merci de votre réponse . J'ai revu les droits du fichier php-errors.log 

Voici les premières traces

2018-02-19 15:09:09 [73@XX-srv-glpi]
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  plugins/racks/front/rack.form.php:82
2018-02-19 15:09:09 [73@XX-srv-glpi]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  plugins/racks/front/rack.form.php:85
2018-02-19 15:09:09 [73@XX-srv-glpi]
  *** PHP Notice(8): Undefined offset: 2
  Backtrace :
  plugins/racks/front/rack.form.php:86

Cdlt

**Comment by amma35** [comment]
C'est un problème de chargement de javascript, il faudrait vider votre cache et bien relancer votre page.

**Comment by Lunaty** [comment]
L'erreur persiste malgré le vidage du cache . Également en erreur sur une autre machine .

**Comment by amma35** [comment]
La liste de vos erreurs sont lorsque vous essayez d'ajouter l'objet c'est normal vu que vous avez un problème de chargement.

Vous n'avez pas d'erreur apache sql ou php lors de la sélection du type ?

**Comment by Lunaty** [comment]
Je vois un carré rouge apparaitre et disparaitre très très rapidement sur le navigateur . Je peux chercher des logs à un autre endroit ?

**Comment by amma35** [comment]
il y a les logs php-errors.log et sql-errors.log, vous êtes bien en mode debug ?

**Comment by tsmr** [comment]
Plugin integrated into GLPI 9.3
I close
