### ISSUE TITLE
Dropdown (second) is not showed because racks.js script not loaded everytime

### ISSUE THREAD

**Issue by mariaczi** [InfotelGLPI/racks#56]
As described in subject of this issue. To have working connected dropdown list we must refresh the page few times. It is very randomly, how many. Sometimes one is enough, sometimes we must do it more then one time.

------------
* Version of the plugin : 1.8.0

* Version of your GLPI : 9.2.3

* Steps to reproduce (which actions have you made) :
- Create new Rack enclosure
- Enter do edit it
- Choose "Fron" or "back" from the left item menu
- Choose Computers/Network Devices etc. 
- The second dropdown list is not showed

* Expected result :
The second dropdown list should be showed.

* Actual result :
The second dropdown list not showed as should.

**Comment by Megachip** [comment]
*sign

**Comment by tsmr** [comment]
Plugin integrated into GLPI 9.3
I close
