### ISSUE TITLE
Add "Move" action on Front/Back for rack enclosuers

### ISSUE THREAD

**Issue by mariaczi** [InfotelGLPI/racks#57]
If it is possible, could you add the new action "Move" in Front/Back in rack enclosures to have easiest and faster possibility to change item position.

Regards.

**Comment by amma35** [comment]
Hi,

We do not make any more evolutions on this plugin because it is included in the GLPI core from version 9.3.

**Comment by mariaczi** [comment]
Thank you very much for your answer and this information.
Regards.

BTW. Will be possible to update glpi 9.2.3 with installed this plugin to version 9.3 without lost data about "rack enclosures"?
