### ISSUE TITLE
Compatible with 9.3?

### ISSUE THREAD

**Issue by dougti** [InfotelGLPI/racks#58]
Hi,
 On Jul 23, 2018 you updated the readme to confirm that the plugin had been integrated into GLPI 9.3, however the current **setup.php** still restricts it to versions >= 9.2 and < 9.3.

Is 9.3 supported or not?

```
109 // Optional : check prerequisites before install : may print errors or add to message after redirect
110 function plugin_racks_check_prerequisites() {
111    if (version_compare(GLPI_VERSION, '9.2', 'lt') || version_compare(GLPI_VERSION, '9.3', 'ge')) {
112       echo __('This plugin requires GLPI >= 9.2');
113       return false;
114    }
115    return true;
116 }
```

**Comment by amma35** [comment]
Hi,

The plugin has been integrated into GLPI so there is no need for the plugin anymore.
