### ISSUE TITLE
Update for GLPI 9.3

### ISSUE THREAD

**Issue by EPTBSGL** [InfotelGLPI/racks#59]
* Version of the plugin : 
1.8.0

* Version of your GLPI : 
9.3.0

Will a version for glpi 9.3 be available soon ?
Thanking you in advance for your answer

**Comment by keha35** [comment]
Hi, 

we already answered in this issue #58

**Comment by EPTBSGL** [comment]
Excuse me. I also found the migration script. Everything works fine. Thank you
